name: CI - Build - Testes

on:
  pull_request:
    branches:
      - [ main, dev ]
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Compilar o projeto
        run: mvn clean compile

      - name: Executar testes
        run: mvn test